// components/ProductFAQ.tsx
// Collapsible FAQ section for product pages.
// Pass the `faqs` array generated by buildFAQs() in the product page.

'use client';

import { useState } from 'react';
import { Icon }     from '@iconify/react';

interface FAQ {
  q: string;
  a: string;
}

export default function ProductFAQ({ faqs }: { faqs: FAQ[] }) {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  if (!faqs?.length) return null;

  return (
    <section className="mt-10 border-t border-gray-100 pt-8">
      <h2 className="text-xl sm:text-2xl font-bold text-gray-900 mb-5">
        Frequently Asked Questions
      </h2>

      <div className="divide-y divide-gray-100">
        {faqs.map((faq, i) => {
          const isOpen = openIndex === i;
          return (
            <div key={i} className="py-4">
              <button
                onClick={() => setOpenIndex(isOpen ? null : i)}
                className="w-full flex items-center justify-between gap-4 text-left"
                aria-expanded={isOpen}
              >
                <span className="text-sm sm:text-base font-semibold text-gray-800 leading-snug">
                  {faq.q}
                </span>
                <Icon
                  icon={isOpen ? 'ph:minus-bold' : 'ph:plus-bold'}
                  className="flex-shrink-0 text-primary"
                  width={18}
                />
              </button>

              {isOpen && (
                <p className="mt-3 text-sm text-gray-600 leading-relaxed pr-8">
                  {faq.a}
                </p>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}